# Generated by Django 3.0.7 on 2022-06-12 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('employee_id', models.CharField(max_length=32)),
                ('current_role', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('compensation', models.FloatField()),
                ('started_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateTimeField()),
                ('cycle_name', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackCycleQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('feedback_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedBackCycle')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Needs Improvement', 'Ni'), ('Meets Expectations', 'Me'), ('Exceeds Expectations', 'Ee'), ('Strongly Exceeds Expectations', 'Se')], default='Meets Expectations', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_author', to='api.Employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedBackCycleQuestions')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_reciever', to='api.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackCycleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to='api.Employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedBackCycleQuestions')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_reciever', to='api.Employee')),
            ],
        ),
    ]
